spring.application.name=optimeal-api
# ----------------------------------------
# PostgreSQL Database Connection
# ----------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/optimeal
spring.datasource.username=postgres
spring.datasource.password=postgres

# ----------------------------------------
# Hibernate & JPA Configuration
# ----------------------------------------
# We use 'validate' because Flyway handles our actual table creation
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true